### ISSUE TITLE
JSON schema?

### ISSUE THREAD

**Issue by danmarshall** [elrumordelaluz/svgson#11]
Hello, thanks again for another fine project!! I am wondering if you have a JSON schema for the output format of the `parse` function?

**Comment by danmarshall** [comment]
First, I was wondering what are the possible values for the `type` property. I see 'element`, but didn't know if it would be `fragment` or `text`. 

Second, I was also looking for a json format for some svg tools, so I also might adopt the same format you have 🤓.

Thirdly - it might make sense to make the `serialize` function a standalone project? That way other tools based on the format do not need the `parse` code. Just a thought 🤷‍♂️

**Comment by elrumordelaluz** [comment]
> First, I was wondering what are the possible values for the type property…

Values for type could be `element` or `text`

> Second, I was also looking for a json format for some svg tools…

Super curious about those tools! 🤓 

> Thirdly - it might make sense to make the serialize function a standalone project?

You mean the [stringify one](https://github.com/elrumordelaluz/svgson#svgsonstringify)? Could absolutely make sense. The thing I am thinking is that `svgson@^3` it should be [tree shakable](https://bundlephobia.com/result?p=svgson@3.0.0) and you could import like

```js
const { stringify } = require('svgson')
```

**Comment by danmarshall** [comment]
Also, I am using TypeScript. So, I will also be doing a conversion from from JSON schema to TypeScript interface.

I may use it in https://github.com/Microsoft/maker.js 
My current build is not es6 based, so I will not be using tree shaking for a while.

**Comment by danmarshall** [comment]
I can use what you've already shared. I thought having a formal schema might also be an easy way to fully document it :)

Please [open an issue](https://github.com/Microsoft/maker.js/issues/new) on Maker.js - would love to know what didn't work for you. 👍 

Yes, `svgson-stringify` could be cool, but don't want to add a maintenance burden.

**Comment by elrumordelaluz** [comment]
> I thought having a formal schema might also be an easy way to fully document it 

Will go with this to update the documentation.

> Please open an issue on Maker.js

sure I will, however I think there isn't an _issue_ directly related on `maker.js`, more on my approach.

**Comment by danmarshall** [comment]
🥇 

The Maker.js GitHub is ok for general discussion 😃

**Comment by jmeurer986** [comment]
Sorry to piggyback on this thread. I couldn't find anyplace else to ask a question. This looks really useful to me. I am a bit new to coding. I am working on a google polymer based app. I think in order to use this I would need to turn this into a web component. Is that something that a novice like me might be able to tackle?

**Comment by elrumordelaluz** [comment]
hi @jmeurer986 it's ok to ask questions as an _issue_ here, if this will become a large thread maybe better to open a new one. I think you could create an `svgson` web-component without problem.
