### ISSUE TITLE
_svgson.default.parse is not a function

### ISSUE THREAD

**Issue by SnooHD** [elrumordelaluz/svgson#12]
Hello,
I figured i should update to the newest svgson, but im not able to get it to work.
I simply used `yarn add svgson`.

Code:
```
let json;
try {
  json = await svgson.parse(optimized);
}catch (error) {
  console.log(error);
}
```

Error:
```
TypeError: _svgson.default.parse is not a function
```

My package.json shows `"svgson": "^3.0.0"`

Any ideas? :)

**Comment by elrumordelaluz** [comment]
Hi @SnooHD 
It's more a documentation _issue_.

If you are using `es` or `cjs`, `svgson` is exported as [default](https://github.com/elrumordelaluz/svgson/blob/f04ed2ac0c1d41cbae266b04430fb70cecfbeb12/src/index-es.js#L3), for `umd` should work as in [readme](https://github.com/elrumordelaluz/svgson#usage).

Recap, the following should work:

```js
import svgson from `svgson`
json = await svgson(optimized)

// or
import { parse } from `svgson`
json = await parse(optimized)
```

Let me know in any case. And I have to fix docs asap.

**Comment by SnooHD** [comment]
Yes `import {parse} from 'svgson';` works fine.
Thank you kindly!! <3
