### ISSUE TITLE
--title in master branch

### ISSUE THREAD

**Issue by cailborg** [elrumordelaluz/svgson#13]
Hi, just wondering if the --title option in v2 is available in the master branch of the CLI tool? I couldn't seem to get it working

**Comment by elrumordelaluz** [comment]
Hi @cailborg, thanks for open the _Issue_.

In the `master` branch lives the last version (`v3`), for `v2` you have to take a look into [this branch](https://github.com/elrumordelaluz/svgson/tree/v2). In that version, the _CLI_ and _node_ version were together (opposed as `v3` where the [cli is a separate package](https://github.com/elrumordelaluz/svgson-cli). 

However `--title` should work in `v2` if you installed locally like `npm i -g svgson@^2` then `svgson -t` (it works on my end).

Let me know in any case.

**Comment by cailborg** [comment]
Excellent, thanks for the response. v2 works great so i'll just stick with that. Thanks!
