### ISSUE TITLE
svgson is not a function

### ISSUE THREAD

**Issue by chris-poe** [elrumordelaluz/svgson#17]
Having problems with the  `Usage` example:

    const svgson = require('svgson');

    svgson(`
      <svg>
        <line
          stroke= "#bada55"
          stroke-width= "2"
          stroke-linecap= "round"
          x1= "70"
          y1= "80"
          x2= "250"
          y2= "150">
        </line>
      </svg>`).then(json => {
        console.log(JSON.stringify(json, null, 2));
      })

Returns: `TypeError: svgson is not a function`

Though console logging `svgson` gives:

    { default: [Function: svgson],
      stringify: [Function: stringify],
      parse: [Function: svgson],
      parseSync: [Function: svgsonSync] }

Calling with `svgson.default('<svg>')` works.

**Environment:**
node: 10.16.0
npm: 6.9.0

**Comment by elrumordelaluz** [comment]
Hi @chris-poe, thanks for open the _Issue_.
Seems to ba a _Docs_ issue, since in the [API section](https://github.com/elrumordelaluz/svgson#api) is well documented.
