### ISSUE TITLE
Can i use this tool to convert my SVG elements to JSON?

### ISSUE THREAD

**Issue by konekoya** [elrumordelaluz/svgson#2]
Hi Lionel,

Sorry if this is not a right place to ask questions.
I'm building a web app which allows users to create SVG based charts with D3.js and then save them.(These charts will then upload to a server) The problem here is that [I cannot convert SVGs to JSONs](http://stackoverflow.com/questions/2303713/how-to-serialize-dom-node-to-json-even-if-there-are-circular-references) and send them to the server. I have googled for a few hours and come across your project. It looks like a good fit for my app. But I'm not quite sure if it's capable of:

1. Can be imported with ES6 module syntax or commonJS? I have read through your docs but still not quite understand the browser part.
2. It seems like it only converts SVGs to JSON but not the reverse?

Thank you! Hope you're doing well!

**Comment by elrumordelaluz** [comment]
Hi @konekoya 
To be honest, I created `svgson` just for the same need you described early. So yes, I'm almost certain that this project could fit well.

Did you try [this syntax](https://github.com/elrumordelaluz/svgson#use-as-node-module). 
Absolutely open to PRs related on ES6 needs (and also to improve the docs)!

> It seems like it only converts SVGs to JSON but not the reverse?

Yes for now only converts in this way (`svg` -> `json`). I am doing the conversion the other way in my _App_. As soon as I can will put this peace of code to show you how.

Let me know,

**Comment by elrumordelaluz** [comment]
@konekoya Just wanted to know if the syntax replied worked for you and in case, close the issue. 

Sorry, but didn't have time to make the lil tool to convert in the opposite way. Will let you know.

**Comment by konekoya** [comment]
Hi @elrumordelaluz 
Sorry for the super late reply! It turned out that I can convert SVGs to base64 -> blob -> send to server with formData.
Have to admit it's not a very good solution, I guess. But that's what I can come up for now.
I will definitely give this plugin a shot again later when I have time.

Thank you for your help and please do keep up your good work in OSS :-)
Joshua
