### ISSUE TITLE
Consider using ^ or ~ versions in package.json

### ISSUE THREAD

**Issue by benwiley4000** [elrumordelaluz/svgson#20]
By making the dependency versions more flexible for downstream users you could decrease the possibility that your package becomes a bottleneck for an `npm audit fix`. I thought of this because I noticed the version we were using of `svgson` depended on a fixed version of `svgo` which had a vulnerability. Turns out the only way I can fix it is to do a major upgrade of `svgson` anyway (it was pre-1.0 svgo), but I noticed you're making lots of commits in the repo just to upgrade dependencies by a patch version increment. You might need to do this less often if you allow flexibility. Downstream users will have their own lockfiles anyway.

Cheers - thanks for sharing the project!

**Comment by elrumordelaluz** [comment]
Hi @benwiley4000, thanks for open the _Issue_. 

Awesome your input! Mind make a PR to fully cover what you means?

**Comment by benwiley4000** [comment]
Sure!
