### ISSUE TITLE
Set required version of `svgo` as at least 1.3.2

### ISSUE THREAD

**Issue by thisismydesign** [elrumordelaluz/svgson#21]
There's an issue with `svgo` which was fixed in 1.3.2: https://github.com/svg/svgo/issues/1174

Our project currently needs to add `"resolutions": { "svgo": "1.3.2" }` to `package.json` when using `svgson` which is only supported by `yarn`. Since `svgson` is our direct requirement, this could be avoided if you made a release with this change and we set that release as a direct minimal requirement.

**Comment by elrumordelaluz** [comment]
Hi @thisismydesign, thanks for open the _Issue_.

Didn't know about that issue but seems super valid to upgrade the `dependency`. 

However `svgo` it isn't a direct [dependency](https://github.com/elrumordelaluz/svgson/blob/master/package.json#L40-L44). Is present in the _reop_ as a `devDependency` to use in [tests](https://github.com/elrumordelaluz/svgson/blob/master/test.js#L188-L206). 

In any case, mind create a PR?

So curious why that `devDependency` is creating an _issue_ in your repo, let me updated.

**Comment by thisismydesign** [comment]
Thanks. You're right, double-checked and the problematic dependency isn't coming from you, sorry. In all likelihood, your usage of `svgo` won't cause problems.
