### ISSUE TITLE
stringify:: Having & symbol rendered in text? 

### ISSUE THREAD

**Issue by itutto** [elrumordelaluz/svgson#27]
I'm manipulating text content with svgson, and occasionally the replacement copy includes & symbol.

**what happens:** 
If there is & symbol in the text value the whole block is converted into CDATA

While the escape function for attributes is overridable, the text part is not. The escapeText function prevents the insertion of & or &amp; symbol. 

`return /[&<>]/.test(str)
      ? // string escaped into cdata
      : // string raw pass `

I would propose to update the regex so HTML entities like &#\d+; and &\w+; are allowed.

**Comment by Serhieieva** [comment]
Issue causes problem with special chars in svg (e.g. &quot;)

**Comment by elrumordelaluz** [comment]
Closing but feel free to re-open in any case.
