### ISSUE TITLE
main source file

### ISSUE THREAD

**Issue by kurundkar123** [elrumordelaluz/svgson#28]
I am new to this library and I want to know the main the file which contains all the functions such as parse and stringify, actully I wanted import these functions in other javascript file.

**Comment by elrumordelaluz** [comment]
Hi @kurundkar123, take a look inside the [/src](https://github.com/elrumordelaluz/svgson/tree/master/src) folder. Everything lives there. Closing since there isn't an _issue_, but feel free to continue asking or re-open in any case.
