### ISSUE TITLE
import files from src folder

### ISSUE THREAD

**Issue by kurundkar123** [elrumordelaluz/svgson#31]
I want to import the svgson file and use the function parse but without using node js but using statically as ES6 module is it possible, like I tried using the same but I couldn't able to do it as I am getting errors like parse is not defined...
Thanking you.

**Comment by elrumordelaluz** [comment]
Hi @kurundkar123. You could test `svgs` directly in the browser [here](https://codepen.io/elrumordelaluz/full/XBKedz/). The simplest way is to import the _package_ `umd` export from [here](https://unpkg.com/svgson@4.1.0/dist/svgson.umd.js).

**Comment by elrumordelaluz** [comment]
cool!
