### ISSUE TITLE
Querying with selectors?

### ISSUE THREAD

**Issue by bgmort** [elrumordelaluz/svgson#41]
Before I write something myself, is there an existing library somewhere to query the svgson tree using CSS-like selectors?

Example:

    const rects = querySelector('#namedGroup rect')
    rects.forEach(rect => {
        rect.attributes.fill = 'red'
    })

**Comment by elrumordelaluz** [comment]
Hi @bgmort, thanks for open the _Issue_.

Don't know, but super curious on what you build over in that case!

**Comment by bgmort** [comment]
@LiamAttClarke thank you! I don't remember what I was wanting to do with it back in August, but that's good info to have.
