### ISSUE TITLE
Updating svgo to latest

### ISSUE THREAD

**Issue by riovir** [elrumordelaluz/svgson#5]
Currently `svgson` uses `svgo@0.6.6` by updating to the latest version of `1.0.5` it'd be possible to use `convertShapeToPath` with circles.

I was trying to merge multiple paths to a single one, when realizing a circle shape is causing problems.

**Comment by elrumordelaluz** [comment]
@riovir you are absolutely right.

did you tried with [svgson-next](https://github.com/elrumordelaluz/svgson-next) which uses the last version (_Promise_ based) of `svgo`?

(I know lacks of _docs_ for now and the API changes a little, but has an option `compat` to match result with `svgson`)

Let me know in each case.

**Comment by riovir** [comment]
I swapped it out, skipping the compat option, changing a few lines in my code instead. Worked like charm. With my problem solved this issue can be closed.

**Comment by elrumordelaluz** [comment]
awesome!
