### ISSUE TITLE
Bump svgo to latest version?

### ISSUE THREAD

**Issue by emmnull** [elrumordelaluz/svgson#50]
Versions of [svgo](https://github.com/svg/svgo) below [3.0.0](https://github.com/svg/svgo/releases/tag/v3.0.0) use a deprecated dep that causes a warning: https://github.com/svg/svgo/issues/1689. This is fixed in more recent versions. Are there plans to bump the version this package uses to a more recent one?

**Comment by elrumordelaluz** [comment]
Hi @iolyd , thanks for open the _Issue_.

`svgson` doesn't have anymore `svgo` as a [dependency](https://github.com/elrumordelaluz/svgson/blob/master/package.json#L42-L46). It is a devDep for some tests/examples. 

Mind however make a PR updating the version of devDep and checking if all tests continue passing?

Thanks!

**Comment by iolyd** [comment]
Oops, my bad! I've lost track of this after resolving it on my side: the warning was indeed stemming from `cssnano` and not from `svgson`.

**Comment by elrumordelaluz** [comment]
Mind sharing more context?

`cssnano` [it isn't a dependency](https://github.com/elrumordelaluz/svgson/blob/master/package.json#L42-L46), neither a hoisted one trying `yarn why cssnano`:

![Screenshot 2023-01-12 at 08 52 13](https://user-images.githubusercontent.com/784056/212008973-12949874-86e9-4734-81e4-ec2e8ece8720.png)
