### ISSUE TITLE
Is repo still active?

### ISSUE THREAD

**Issue by emn-dev** [elrumordelaluz/svgson#52]
Hi! We are just checking to see if the repo is still actively maintained?

thanks!

**Comment by elrumordelaluz** [comment]
Hi @emn-dev please let know if there is something missing. Thanks!

**Comment by emn-dev** [comment]
Hi @elrumordelaluz ! We have a small team of developers and we use and like svgson :) We were interested to see if you might be willing to transfer to us? We are looking to get more involved, as a team, in open source. This project (and npm package = https://www.npmjs.com/package/svgson) is something we would like to maintain and maybe add some new things (e.g. esbuild) and maybe reduce/remove dependencies. I certainly don't want to take anything away from you... nothing like that... we just want to be able to make changes and not have to wait on approvals... so we can move at our own speed. What do you think about that?

**Comment by emn-dev** [comment]
If you want to know more about us and what we do I'm happy to send email or private message somewhere :)

**Comment by elrumordelaluz** [comment]
> We were interested to see if you might be willing to transfer to us?

What do you mean? Is not enough for you to use and collaborate in OSS?

> …is something we would like to maintain and maybe add some new things (e.g. esbuild) and maybe reduce/remove dependencies.

I think the way to make part of a lib / software is to start collaborating. Did you tried to make a PR before or just wrote about the status of the repo? I have no doubt about the absolutely quality the software can have through OSS and collaborating. Why don't you try to collaborate before ask transfer of things like this. I am sure each repo owner is ready to add maintainers when they are proactive. 

> If you want to know more about us and what we do I'm happy to send email or private message somewhere :)

Finally I think it is not necessary to know who or which company is behind the new collaborator, the important point is what they do, improve, add, remove and discuss.

Have a nice OSS collaborating journey. Best,

**Comment by emn-dev** [comment]
@elrumordelaluz you are absolutely right... I definitely approached this wrong. Sorry about that. Let me put up a PR and see if there are improvements that work for everyone. :)
