### ISSUE TITLE
Special characters generate weird CDATA tag?

### ISSUE THREAD

**Issue by OfficialCRUGG** [elrumordelaluz/svgson#58]
Hey there!

I am currently trying to use svgson to do some bulk operations on some icons.

The source SVG includes `<title>Aerom&#233;xico</title>`, but when running this through svgson, it returns `<title><![CDATA[Aerom&#233;xico]]></title>` which causes further issues due to not being a valid HTML tag.

Is there any way to fix this?

**Comment by elrumordelaluz** [comment]
Hi @OfficialCRUGG, thanks for open the _Issue_.

You have to make use of `transformNode` option of [stringify](https://github.com/elrumordelaluz/svgson#svgsonstringify), which allow you to transform each node. In this case, you want to `decode` html entities. I presume you are in a nodejs env (and not browser), so you have to do it with something like [this lib](https://www.npmjs.com/package/entities).

Here is an example of `transformNode` function:

```js
function transformNode(node) {
  return {
    ...node,
    ...(node.children ? { children: node.children.map(transformNode) } : {}),
    value: entities.decodeHTML(node.value),
  };
}
```

and here is a [working example](https://codesandbox.io/p/sandbox/exciting-engelbart-mm4ynk?file=%2Fpackage.json%3A15%2C20).

**Comment by OfficialCRUGG** [comment]
There doesn't seem to be any `tramsformNode` option in the type definitions, @elrumordelaluz?

![image](https://github.com/elrumordelaluz/svgson/assets/25248999/db303a13-4699-4a34-893d-a4efa3be6662)

**Comment by elrumordelaluz** [comment]
what `svgson` are you using? Thanks to your _issue_ I found that this prop wasn't included in [types](https://github.com/elrumordelaluz/svgson/blob/master/types.d.ts#L19). can you please update in case?

**Comment by OfficialCRUGG** [comment]
Updated from 5.3.0 to 5.3.1 and that solved it. Thanks.
