### ISSUE TITLE
Order of SVG elements

### ISSUE THREAD

**Issue by amitguptagwl** [elrumordelaluz/svgson#6]
For a SVG [order of the elements](https://stackoverflow.com/questions/17786618/how-to-use-z-index-in-svg-elements) is important. On the other side as per ECMAScript standards, a js object doesn't guarantee the key order. So does this library maintains the order of SVG elements?

**Comment by elrumordelaluz** [comment]
hey @amitguptagwl thanks for reaching,
Since the parsed `children` is always an `Array` should be the same order.

Let me know if you have a specific case where this won't work as expected.
