### ISSUE TITLE
How to convert JSON to SVG?

### ISSUE THREAD

**Issue by ceremcem** [elrumordelaluz/svgson#7]
How can we convert the edited JSON back to SVG?

**Comment by elrumordelaluz** [comment]
hey @ceremcem thanks for the answer, I encourage you to use [svgson-next](https://github.com/elrumordelaluz/svgson-next) which will be (probably later today or in the next days) the new major version of `svgson` for lot of reasons (bundle size, etc), included the one that have a method called `stringify`.

You could use it this way:
```js
const { stringify } = require('svgson-next')
const svgsonObject = { /* ... */ }
stringify(svgsonObject)
```

Let me know in any case.

**Comment by ceremcem** [comment]
`svgson-next` nicely solves the case, thank you.
